create table if not exists familias (
    id bigint generated by default as identity primary key,
    sobrenome text not null,
    endereco text not null,
    created_at timestamptz not null default now()
);

create table if not exists membros (
    id bigint generated by default as identity primary key,
    nome text not null,
    telefone text not null,
    nascimento date not null,
    familia_id bigint not null references familias(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table familias enable row level security;
alter table membros enable row level security;

create policy "Permitir leitura publica de familias"
on familias for select
to anon
using (true);

create policy "Permitir cadastro publico de familias"
on familias for insert
to anon
with check (true);

create policy "Permitir leitura publica de membros"
on membros for select
to anon
using (true);

create policy "Permitir cadastro publico de membros"
on membros for insert
to anon
with check (true);


create policy "Permitir edicao publica de familias"
on familias for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de familias"
on familias for delete
to anon
using (true);


create policy "Permitir edicao publica de membros"
on membros for update
to anon
using (true)
with check (true);

create policy "Permitir exclusao publica de membros"
on membros for delete
to anon
using (true);
